{% set name = "dbt-snowflake" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b41a10868ba81d105304b71b45f09a10cdc166ec20088031efb5190542297272

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    # via Grayskull
    - dbt-adapters >=1.10.4,<2.0
    - dbt-common >=1.10,<2.0
    - python >={{ python_min }}
    - dbt-core >=1.8.0
    - snowflake-connector-python >=3.0,<4.dev0
    - agate

test:
  imports:
    - dbt.adapters.snowflake
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-snowflake
  summary: The Snowflake adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
