{% set name = "dbt-snowflake" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 70ad763e334119fb7af96a924f6a2c67a873ffc1c4f5a4723b7948825c4de399

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    # via Grayskull
    - dbt-adapters >=1.10.4,<2.0
    - dbt-common >=1.10,<2.0
    - dbt-core >=1.8.0
    - snowflake-connector-python >=3.0,<4.dev0
    - agate

test:
  imports:
    - dbt.adapters.snowflake
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/dbt-labs/dbt-snowflake
  summary: The Snowflake adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
