{% set name = "dbt-snowflake" %}
{% set version = "1.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fba7b9f86c4ddb4bb74f9616a0115206edc460c36af33f6354529fa9a0e12c1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.16.6,<2.0
    - snowflake-connector-python >=3.17.2,<4.0.0
    - certifi <2025.4.26
    - dbt-core >=1.10.0rc0
    - agate

test:
  imports:
    - dbt.adapters.snowflake
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-snowflake
  summary: The Snowflake adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
