schema_version: 1

context:
  name: dbt-snowflake
  version: 1.10.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 00aa69dd6a3d9fb8204c14cbcc8d54fc90ff8b357cbe2f5a5e5812b4de99b61a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - python >=${{ python_min }}
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.22.2,<2.0
    - snowflake-connector-python >=4.0.0,<5.0.0
    - certifi <2025.4.26
    - dbt-core >=1.10.0rc0
    - agate
tests:
  - python:
      imports:
        - dbt.adapters.snowflake
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The Snowflake adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/dbt-labs/dbt-snowflake

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
